export const STRATEGIC_LEVERS = [
  "marktuitbreiding",
  "nieuwe segmenten",
  "geografische expansie",
  "prijsstrategie",
  "volumegroei",
  "productiviteit",
  "automatisering",
  "capaciteitsbenutting",
  "procesoptimalisatie",
  "supply chain",
  "kostenstructuur",
  "margeverbetering",
  "kapitaalallocatie",
  "investeringsdiscipline",
  "schaalvoordelen",
  "positionering",
  "merkautoriteit",
  "distributiemacht",
  "ecosystemen",
  "netwerkstrategieën",
  "governance",
  "leiderschap",
  "cultuur",
  "talentstrategie",
  "incentive structuur",
  "data-infrastructuur",
  "besluitritme",
] as const;

export type StrategicLever = (typeof STRATEGIC_LEVERS)[number];

export type StrategicLeverDefinition = {
  lever: StrategicLever;
  category:
    | "groei"
    | "operatie"
    | "financieel"
    | "positie"
    | "organisatie"
    | "informatie";
  mechanismCluster:
    | "omzetgroei"
    | "efficiency"
    | "rendement"
    | "marktmacht"
    | "executiekracht"
    | "strategische snelheid";
  patterns: RegExp[];
  mechanism: string;
  risk: string;
  boardImplication: string;
};

export const STRATEGIC_LEVER_MATRIX: StrategicLeverDefinition[] = [
  {
    lever: "marktuitbreiding",
    category: "groei",
    mechanismCluster: "omzetgroei",
    patterns: [/\bmarktuitbreiding\b/i, /\bnieuwe markt(en)?\b/i, /\buitbreiden naar\b/i],
    mechanism: "Omzet groeit wanneer het bestaande model in aanpalende markten wordt herhaald zonder de kernpropositie te verdunnen.",
    risk: "Marktuitbreiding zonder scherp toegangsmodel vergroot commerciële kosten en bestuurlijke afleiding.",
    boardImplication: "Bestuur moet expliciet bepalen welke markt wel en niet binnen de kernscope valt.",
  },
  {
    lever: "nieuwe segmenten",
    category: "groei",
    mechanismCluster: "omzetgroei",
    patterns: [/\bsegment(en)?\b/i, /\bdoelgroep(en)?\b/i, /\bnieuw(e)? cliëntgroep\b/i],
    mechanism: "Omzet groeit wanneer dezelfde capability wordt ingezet voor een segment met hogere strategische fit.",
    risk: "Segmentverbreding kan capaciteit versnipperen en de propositie diffuser maken.",
    boardImplication: "Bestuur moet segmentcriteria en stopregels voor niet-passende vraag vastleggen.",
  },
  {
    lever: "geografische expansie",
    category: "groei",
    mechanismCluster: "omzetgroei",
    patterns: [/\bregio\b/i, /\bregionaal\b/i, /\bgeografische expansie\b/i, /\blocatie(s)?\b/i],
    mechanism: "Omzet groeit wanneer regionale expansie de replicatie van een bewezen model versnelt.",
    risk: "Geografische spreiding zonder governance-ritme vergroot kwaliteitsvariatie.",
    boardImplication: "Bestuur moet kiezen waar expansie governance-technisch nog bestuurbaar blijft.",
  },
  {
    lever: "prijsstrategie",
    category: "groei",
    mechanismCluster: "omzetgroei",
    patterns: [/\bprijs\b/i, /\btarief\b/i, /\bvergoeding\b/i, /\bcontract\b/i],
    mechanism: "Omzetkwaliteit groeit wanneer prijs en contractmix beter aansluiten op waardecreatie.",
    risk: "Prijsdruk of verkeerde contractmix trekt groei los van rendement.",
    boardImplication: "Bestuur moet prijsgrenzen en onderhandelingsmandaat expliciet maken.",
  },
  {
    lever: "volumegroei",
    category: "groei",
    mechanismCluster: "omzetgroei",
    patterns: [/\bvolume\b/i, /\binstroom\b/i, /\bgroei\b/i, /\bcliënten\b/i],
    mechanism: "Omzet groeit wanneer extra volume wordt toegelaten zonder het dominante schaalmechanisme te breken.",
    risk: "Lineaire volumegroei kan cultuur, kwaliteit en voorspelbaarheid aantasten.",
    boardImplication: "Bestuur moet vastleggen welk volume strategisch gewenst is en wanneer een groeistop geldt.",
  },
  {
    lever: "productiviteit",
    category: "operatie",
    mechanismCluster: "efficiency",
    patterns: [/\bproductiviteit\b/i, /\bthroughput\b/i, /\bdoorstroom\b/i],
    mechanism: "Efficiency groeit wanneer dezelfde capaciteit structureel meer output levert.",
    risk: "Productiviteitsdruk zonder kwaliteitsguardrails veroorzaakt onderstroom en uitval.",
    boardImplication: "Bestuur moet productiviteitsnormen koppelen aan kwaliteitsdrempels.",
  },
  {
    lever: "automatisering",
    category: "operatie",
    mechanismCluster: "efficiency",
    patterns: [/\bautomat(iseer|isering)\b/i, /\bdigitalisering\b/i, /\bworkflow\b/i],
    mechanism: "Efficiency groeit wanneer repeterende taken uit de besluit- en uitvoeringsketen worden gehaald.",
    risk: "Automatisering zonder procesdiscipline kan ruis alleen sneller opschalen.",
    boardImplication: "Bestuur moet automatisering alleen toestaan waar eigenaarschap en datakwaliteit op orde zijn.",
  },
  {
    lever: "capaciteitsbenutting",
    category: "operatie",
    mechanismCluster: "efficiency",
    patterns: [/\bcapaciteit\b/i, /\btriage\b/i, /\bbenutting\b/i, /\bwachtdruk\b/i],
    mechanism: "Efficiency groeit wanneer bestaande capaciteit via betere triage en planning meer waarde levert.",
    risk: "Hogere benutting kan diagnosekwaliteit of teamduurzaamheid aantasten.",
    boardImplication: "Bestuur moet capaciteitsdoelen altijd koppelen aan klinische of kwaliteitsmonitoring.",
  },
  {
    lever: "procesoptimalisatie",
    category: "operatie",
    mechanismCluster: "efficiency",
    patterns: [/\bproces\b/i, /\bstandaardisatie\b/i, /\boptimalisatie\b/i],
    mechanism: "Efficiency groeit wanneer variatie uit de kernworkflow wordt gehaald.",
    risk: "Procesoptimalisatie kan lokale efficiëntie boven strategische waarde stellen.",
    boardImplication: "Bestuur moet bepalen welke processen standaard zijn en waar maatwerk verplicht blijft.",
  },
  {
    lever: "supply chain",
    category: "operatie",
    mechanismCluster: "efficiency",
    patterns: [/\bsupply chain\b/i, /\bketen\b/i, /\bdoorlevering\b/i, /\binstroomkanaal\b/i],
    mechanism: "Efficiency groeit wanneer afhankelijkheden in de keten beter worden geregisseerd.",
    risk: "Ketenfrictie kan interne teams belasten zonder dat doorstroom verbetert.",
    boardImplication: "Bestuur moet bepalen welke ketenpartners kritisch zijn en welke SLA's bindend worden.",
  },
  {
    lever: "kostenstructuur",
    category: "financieel",
    mechanismCluster: "rendement",
    patterns: [/\bkost(en)?\b/i, /\bloonkosten\b/i, /\bkostenstructuur\b/i],
    mechanism: "Rendement groeit wanneer de kostenbasis opnieuw wordt ingericht rond het werkelijke schaalmechanisme.",
    risk: "Een starre kostenstructuur slokt marge op voordat schaal rendeert.",
    boardImplication: "Bestuur moet vastleggen welke kosten vast, variabel of stopbaar zijn.",
  },
  {
    lever: "margeverbetering",
    category: "financieel",
    mechanismCluster: "rendement",
    patterns: [/\bmarge\b/i, /\brendement\b/i, /\bbrutomarge\b/i],
    mechanism: "Rendement groeit wanneer omzetkwaliteit sneller verbetert dan operationele belasting.",
    risk: "Margeverbetering zonder contract- en portfoliokeuze blijft cosmetisch.",
    boardImplication: "Bestuur moet marge expliciet meenemen in prioritering en stopbesluiten.",
  },
  {
    lever: "kapitaalallocatie",
    category: "financieel",
    mechanismCluster: "rendement",
    patterns: [/\bkapitaalallocatie\b/i, /\bkapitaal\b/i, /\bcash\b/i, /\bliquiditeit\b/i],
    mechanism: "Rendement groeit wanneer kapitaal selectief naar het dominante schaalpad gaat.",
    risk: "Versnipperde allocatie vertraagt executie en houdt zwakke initiatieven kunstmatig in leven.",
    boardImplication: "Bestuur moet kapitaal toewijzen op basis van strategische prioriteit en stopregels.",
  },
  {
    lever: "investeringsdiscipline",
    category: "financieel",
    mechanismCluster: "rendement",
    patterns: [/\binvestering(en)?\b/i, /\bbusiness case\b/i, /\bcapex\b/i],
    mechanism: "Rendement groeit wanneer investeringen alleen doorgaan met aantoonbare strategische terugverdienlogica.",
    risk: "Te veel parallelle investeringen vergroten bestuurlijke ruis en vertragen rendement.",
    boardImplication: "Bestuur moet één investeringskader hanteren voor alle strategische initiatieven.",
  },
  {
    lever: "schaalvoordelen",
    category: "financieel",
    mechanismCluster: "rendement",
    patterns: [/\bschaalvoordeel(en)?\b/i, /\blearning curve\b/i, /\bshared service\b/i],
    mechanism: "Rendement groeit wanneer schaal leidt tot lagere gemiddelde kosten of hogere herhaalbaarheid.",
    risk: "Veronderstelde schaalvoordelen blijven uit als het model niet echt repliceerbaar is.",
    boardImplication: "Bestuur moet aantonen welke schaalvoordelen echt optreden en welke alleen worden verondersteld.",
  },
  {
    lever: "positionering",
    category: "positie",
    mechanismCluster: "marktmacht",
    patterns: [/\bpositionering\b/i, /\bpropositie\b/i, /\bonderscheid(end)?\b/i, /\bmarktpositie\b/i],
    mechanism: "Marktmacht groeit wanneer de organisatie scherper kiest welk probleem zij uniek oplost.",
    risk: "Diffuse positionering leidt tot prijsdruk en versnipperde vraag.",
    boardImplication: "Bestuur moet kernpropositie, doelspelers en uitsluitingen expliciteren.",
  },
  {
    lever: "merkautoriteit",
    category: "positie",
    mechanismCluster: "marktmacht",
    patterns: [/\bmerk\b/i, /\breputatie\b/i, /\bautoriteit\b/i],
    mechanism: "Marktmacht groeit wanneer vertrouwen het verschil maakt in toegang, pricing en partnerkeuze.",
    risk: "Reputatieschade werkt disproportioneel door in contractering en adoptie.",
    boardImplication: "Bestuur moet bepalen welke kwaliteitsclaims permanent verdedigbaar moeten zijn.",
  },
  {
    lever: "distributiemacht",
    category: "positie",
    mechanismCluster: "marktmacht",
    patterns: [/\bdistributie\b/i, /\bkanaal\b/i, /\btoegang\b/i, /\bverwijzer(s)?\b/i],
    mechanism: "Marktmacht groeit wanneer toegangspaden beter zijn dan die van alternatieven.",
    risk: "Afhankelijkheid van zwakke kanalen houdt instroom en marge kwetsbaar.",
    boardImplication: "Bestuur moet kiezen welke kanalen strategisch dominant worden en welke worden afgebouwd.",
  },
  {
    lever: "ecosystemen",
    category: "positie",
    mechanismCluster: "marktmacht",
    patterns: [/\becosysteem\b/i, /\bcoalitie\b/i, /\bplatform\b/i, /\balliantie\b/i],
    mechanism: "Marktmacht groeit wanneer de organisatie knooppunt wordt in een breder waardesysteem.",
    risk: "Ecosysteemrollen zonder heldere governance creëren diffuse verantwoordelijkheid.",
    boardImplication: "Bestuur moet de gewenste rol in het ecosysteem en bijbehorend mandaat expliciteren.",
  },
  {
    lever: "netwerkstrategieën",
    category: "positie",
    mechanismCluster: "marktmacht",
    patterns: [/\bnetwerk\b/i, /\bpartner(s)?\b/i, /\blicentie\b/i, /\bnetwerkstrategie(ën)?\b/i],
    mechanism: "Marktmacht groeit wanneer impact via partners sneller schaalt dan interne personeelscapaciteit.",
    risk: "Verlies van kwaliteitscontrole kan de hefboom neutraliseren.",
    boardImplication: "Bestuur moet een governance-model kiezen voor partnerselectie, auditing en escalatie.",
  },
  {
    lever: "governance",
    category: "organisatie",
    mechanismCluster: "executiekracht",
    patterns: [/\bgovernance\b/i, /\bmandaat\b/i, /\bescalatie\b/i, /\bboard\b/i],
    mechanism: "Executiekracht groeit wanneer besluitrecht, eigenaarschap en stopregels scherp zijn.",
    risk: "Diffuus mandaat vertraagt uitvoering en houdt conflicterende prioriteiten in leven.",
    boardImplication: "Bestuur moet besluitrechten, eigenaarschap en escalatieritme vastleggen.",
  },
  {
    lever: "leiderschap",
    category: "organisatie",
    mechanismCluster: "executiekracht",
    patterns: [/\bleiderschap\b/i, /\bdirectie\b/i, /\bmanagement\b/i],
    mechanism: "Executiekracht groeit wanneer leiderschap strategische keuzes consequent vertaalt naar prioriteiten.",
    risk: "Leiderschapsinconsistentie vergroot interpretatieruimte en vertraagt adoptie.",
    boardImplication: "Bestuur moet rolverdeling en voorbeeldgedrag expliciet maken.",
  },
  {
    lever: "cultuur",
    category: "organisatie",
    mechanismCluster: "executiekracht",
    patterns: [/\bcultuur\b/i, /\beigenaarschap\b/i, /\bwerkplezier\b/i, /\bziekteverzuim\b/i],
    mechanism: "Executiekracht groeit wanneer cultuur kwaliteit, retentie en discipline draagt.",
    risk: "Schaaldruk kan het cultuurmechanisme sneller aantasten dan dashboards zichtbaar maken.",
    boardImplication: "Bestuur moet vastleggen welke cultuurkenmerken niet onderhandelbaar zijn.",
  },
  {
    lever: "talentstrategie",
    category: "organisatie",
    mechanismCluster: "executiekracht",
    patterns: [/\btalent\b/i, /\bretentie\b/i, /\bwerving\b/i, /\bopleiden\b/i],
    mechanism: "Executiekracht groeit wanneer talentstromen aansluiten op de strategische koers.",
    risk: "Werving zonder model-fit vergroot overhead en verlaagt kwaliteitsconsistentie.",
    boardImplication: "Bestuur moet bepalen welke profielen kernkritisch zijn en hoe retentie wordt bewaakt.",
  },
  {
    lever: "incentive structuur",
    category: "organisatie",
    mechanismCluster: "executiekracht",
    patterns: [/\bincentive\b/i, /\bbeloning\b/i, /\bprikkel(s)?\b/i, /\bbonus\b/i],
    mechanism: "Executiekracht groeit wanneer prikkels dezelfde richting versterken als de strategie.",
    risk: "Verkeerde incentives belonen lokaal succes ten koste van systeemwaarde.",
    boardImplication: "Bestuur moet incentives herontwerpen rond strategische uitkomsten in plaats van losse output.",
  },
  {
    lever: "data-infrastructuur",
    category: "informatie",
    mechanismCluster: "strategische snelheid",
    patterns: [/\bdata\b/i, /\bdashboard\b/i, /\bdata-infrastructuur\b/i, /\bmonitoring\b/i],
    mechanism: "Strategische snelheid groeit wanneer data direct besluitvorming en correctie voedt.",
    risk: "Slechte datakwaliteit creëert schijnzekerheid en vertraagt herbesluitvorming.",
    boardImplication: "Bestuur moet bepalen welke stuurdata bindend, ritmisch en bronvast wordt gemaakt.",
  },
  {
    lever: "besluitritme",
    category: "informatie",
    mechanismCluster: "strategische snelheid",
    patterns: [/\bbesluitritme\b/i, /\britme\b/i, /\bkpi\b/i, /\breview\b/i],
    mechanism: "Strategische snelheid groeit wanneer afwijkingen snel leiden tot bestuurlijke correctie.",
    risk: "Te traag besluitritme laat onderliggende drift groter worden dan nodig.",
    boardImplication: "Bestuur moet vaste review- en herbesluitmomenten afdwingbaar maken.",
  },
] as const;
