import { CyntraDesignTokens } from "@/design/cyntraDesignTokens";
import { reportDesignSystem } from "@/design/reportDesignSystem";

const gold = CyntraDesignTokens.colors.gold;
const titleSize = 20;
const bodySize = 16;
const metaSize = 12;
const maxWidth = 1280;

export const reportViewStyles = {
  layout: {
    root: `mx-auto max-w-[${maxWidth}px] space-y-12 bg-white px-8 py-12 text-black md:px-12 xl:px-20`,
    header: "space-y-5",
    sections: "space-y-12",
    grid12: "grid grid-cols-1 gap-6 xl:grid-cols-12",
    column6: "xl:col-span-6",
    column12: "xl:col-span-12",
  },
  header: {
    label: `text-[${metaSize}px] font-semibold uppercase tracking-[0.28em] text-[#6b7280]`,
    title: "max-w-3xl font-['Aptos_Display','Aptos','Segoe_UI',sans-serif] text-[30px] font-semibold leading-[1.12] tracking-[-0.03em] text-black md:text-[40px]",
    subtitle: `max-w-[620px] font-['Aptos','Segoe_UI',sans-serif] text-[${bodySize}px] leading-[1.75] text-[#4b5563]`,
    meta: "flex flex-wrap gap-x-4 gap-y-2 text-[12px] text-[#6b7280]",
  },
  section: {
    root: "space-y-5",
    number: `text-[${metaSize}px] font-semibold uppercase tracking-[0.28em] text-[#6b7280]`,
    title: `font-['Aptos_Display','Aptos','Segoe_UI',sans-serif] text-[${titleSize}px] font-semibold tracking-[-0.02em] text-black md:text-[26px]`,
    rule: "h-px w-16 bg-black/10",
    paragraph: `max-w-[620px] whitespace-pre-wrap font-['Aptos','Segoe_UI',sans-serif] text-[${bodySize}px] leading-[1.75] text-[#111827]`,
    paragraphCompact: `max-w-[620px] font-['Aptos','Segoe_UI',sans-serif] text-[15px] leading-[1.75] text-[#111827]`,
    emphasizedParagraph: `max-w-[620px] whitespace-pre-wrap font-['Aptos','Segoe_UI',sans-serif] text-[${bodySize}px] font-medium leading-[1.75] text-black`,
    muted: "text-[15px] text-[#6b7280]",
    bulletList: "space-y-2 pl-5",
    bulletListCompact: "space-y-1.5 pl-5",
    accentBulletList: "space-y-4",
    bullet: "font-['Aptos','Segoe_UI',sans-serif] text-[15px] leading-[1.75] text-[#111827]",
    bulletCompact: "font-['Aptos','Segoe_UI',sans-serif] text-[15px] leading-[1.75] text-[#111827]",
    accentBullet: "px-0 py-0 font-['Aptos','Segoe_UI',sans-serif] text-[15px] leading-[1.75] text-[#111827]",
    action: "rounded-full bg-black px-4 py-2 text-[13px] font-medium text-white transition hover:bg-black/85",
    subheading: "text-[12px] font-semibold uppercase tracking-[0.24em] text-[#6b7280]",
  },
  panel: {
    root: "space-y-4",
    title: "text-[20px] font-semibold tracking-[-0.02em] text-black",
    body: "whitespace-pre-wrap text-[15px] leading-[1.75] text-black",
    mutedBody: "text-[14px] leading-7 text-[#4b5563]",
    list: "space-y-2 text-[14px] leading-7 text-[#374151]",
    criticalList: "space-y-2 text-[14px] leading-7 text-[#7f1d1d]",
    warningList: "space-y-2 text-[14px] leading-7 text-[#92400e]",
  },
  decisionCard: {
    root: "space-y-8 rounded-[12px] border border-white/[0.06] bg-[rgba(255,255,255,0.02)] p-8",
    label: `text-[12px] font-semibold uppercase tracking-[0.24em] text-[${gold}]`,
    question: "max-w-3xl font-['Aptos','Segoe_UI',sans-serif] text-[16px] font-semibold leading-[1.5] text-white md:text-[17px]",
    metaGrid: "grid gap-4 md:grid-cols-3",
    metaLabel: "text-[11px] uppercase tracking-[0.24em] text-slate-500",
    metaValue: "text-[15px] font-medium text-slate-200",
    heroGrid: "grid grid-cols-1 gap-6 xl:grid-cols-12",
    heroPrimary: "space-y-6 xl:col-span-8",
    heroAside: "space-y-4 xl:col-span-4",
    statement: "max-w-3xl font-['Aptos','Segoe_UI',sans-serif] text-[16px] font-medium leading-[1.7] text-slate-100",
    section: "space-y-2",
    sectionTitle: "text-[12px] uppercase tracking-[0.2em] text-slate-400",
    sectionBody: "text-[15px] leading-[1.6] text-slate-100",
    bulletList: "space-y-2 pl-4 text-[15px] leading-[1.6] text-slate-200 list-disc",
    bullet: "pl-1",
    stopRules: "space-y-2",
    asideCard: "rounded-[12px] border border-white/[0.06] bg-[rgba(255,255,255,0.02)] p-6",
  },
  cockpit: {
    panel: "space-y-8",
    panelTitle: "text-[24px] font-semibold tracking-[-0.03em] text-black md:text-[30px]",
    panelText: "max-w-[620px] text-[15px] leading-[1.8] text-[#374151]",
    tensionWrap: "space-y-10",
    tensionAxis: "space-y-8",
    tensionLabelRow: "flex items-center justify-between gap-6 flex-nowrap text-[11px] font-semibold uppercase tracking-[0.22em] text-[#6b7280]",
    tensionTrack: "relative h-28",
    tensionLine: "absolute left-8 right-8 top-1/2 h-px -translate-y-1/2 bg-black/20",
    tensionPoleTop: "absolute left-0 top-1/2 flex -translate-y-1/2 flex-col items-start gap-2",
    tensionPoleBottom: "absolute right-0 top-1/2 flex -translate-y-1/2 flex-col items-end gap-2",
    tensionDot: "h-4 w-4 rounded-full border border-black/40 bg-white",
    tensionCurrent: "absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-2",
    tensionCurrentDot: "h-5 w-5 rounded-full border border-black bg-black",
    tensionCurrentLabel: "px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-black",
    scenarioGrid: "grid grid-cols-1 gap-4 xl:grid-cols-3",
    scenarioCard: "space-y-4",
    scenarioCardRecommended: "",
    scenarioCode: "text-[12px] font-semibold uppercase tracking-[0.24em] text-[#6b7280]",
    scenarioTitle: "text-[18px] font-semibold tracking-[-0.02em] text-black",
    scenarioBadge: "inline-flex items-center gap-2 px-0 py-1 text-[11px] font-semibold uppercase tracking-[0.2em] text-black",
    scenarioLabel: "text-[11px] uppercase tracking-[0.2em] text-[#6b7280]",
    timelineGrid: "grid grid-cols-1 gap-4 xl:grid-cols-3",
    timelineColumn: "space-y-5",
    timelineCard: "space-y-3",
    signalGrid: "grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4",
    signalCard: "space-y-4",
    signalValue: "text-[15px] leading-[1.75] text-black",
    signalRiskHigh: "inline-flex px-0 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#7f1d1d]",
    signalRiskMedium: "inline-flex px-0 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#92400e]",
    signalRiskLow: "inline-flex px-0 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#166534]",
    analysisStack: "space-y-4",
    analysisDisclosure: "space-y-4",
    analysisSummary: "cursor-pointer list-none text-[16px] font-semibold text-black [&::-webkit-details-marker]:hidden",
    analysisBody: "mt-4 text-[16px] leading-[1.7] text-[#374151]",
  },
  board: {
    shell: `mx-auto max-w-[${maxWidth}px] bg-white px-8 py-10 font-['Aptos','Segoe_UI',sans-serif] text-black md:px-12 xl:px-20`,
    topbar: "sticky top-0 z-20 mb-12 flex flex-wrap items-center gap-5 bg-white/94 py-4 backdrop-blur",
    navButton: "inline-flex items-center px-0 py-0 text-[13px] font-normal text-[#6b7280] transition hover:text-black",
    section: "space-y-8 py-12",
    sectionDark: "space-y-6 bg-[#111111] px-8 py-12 text-white md:px-12 xl:px-20",
    eyebrow: "text-[13px] font-normal uppercase tracking-[0.16em] text-[#6b7280]",
    eyebrowDark: "text-[13px] font-normal uppercase tracking-[0.16em] text-white/55",
    sectionTitle: "font-['Aptos','Segoe_UI',sans-serif] text-[20px] font-normal leading-[1.35] text-black",
    sectionTitleDark: "font-['Aptos','Segoe_UI',sans-serif] text-[20px] font-normal leading-[1.35] text-white",
    body: "max-w-[600px] text-[16px] font-normal leading-[1.75] text-[#374151]",
    bodyDark: "max-w-[600px] text-[16px] font-normal leading-[1.75] text-white/78",
    bulletList: "max-w-[600px] list-disc space-y-3 pl-5 text-[16px] font-normal leading-[1.75] text-[#374151]",
    bulletListDark: "max-w-[600px] list-disc space-y-2 pl-5 text-[16px] font-normal leading-[1.75] text-white/82",
    rowGrid: "grid gap-y-6 md:grid-cols-2 md:gap-x-10",
    rowTitle: "max-w-[600px] text-[16px] font-normal leading-[1.6] text-black",
    rowTitleDark: "max-w-[600px] text-[16px] font-normal leading-[1.6] text-white",
    meta: "text-[13px] font-normal uppercase tracking-[0.14em] text-[#6b7280]",
    metaDark: "text-[13px] font-normal uppercase tracking-[0.14em] text-white/55",
    decisionHeadline: "max-w-[600px] font-['Aptos','Segoe_UI',sans-serif] text-[32px] font-normal leading-[1.22] tracking-[-0.02em] text-white",
    decisionHeadlineLight: "max-w-[600px] font-['Aptos','Segoe_UI',sans-serif] text-[32px] font-normal leading-[1.22] tracking-[-0.02em] text-black",
    intro: "max-w-[600px] text-[16px] font-normal leading-[1.75] text-black",
    introMuted: "max-w-[600px] text-[13px] font-normal leading-[1.65] text-[#6b7280]",
  },
} as const;

export const reportViewStyleMeta = {
  designSystem: reportDesignSystem.identity.name,
  allowedParagraphHighlights: reportDesignSystem.emphasis.allowedParagraphHighlights,
  allowedAccentLists: reportDesignSystem.emphasis.allowedAccentLists,
} as const;
