const PRESENTATION_TITLES: Record<string, string> = {
  "BESLUIT": "Besluit",
  "BESLUITVRAAG": "Besluitvraag",
  "SITUATIE": "Situatie",
  "SPANNING": "Spanning",
  "STRATEGISCHE SPANNING": "Strategische spanning",
  "WAAROM DIT GEBEURT": "Waarom dit gebeurt",
  "MECHANISME ANALYSE": "Mechanisme-analyse",
  "SCENARIO'S": "Scenario's",
  "SCENARIOVERGELIJKING": "Scenariovergelijking",
  "BESTUURLIJKE IMPLICATIES": "Bestuurlijke implicaties",
  "STOPREGELS": "Stopregels",
  "EXECUTIVE DECISION CARD": "Executive Decision Card",
  "STRATEGISCH VERHAAL": "Strategisch verhaal",
  "BESTUURLIJKE ACTIES": "Bestuurlijke acties",
  "VERDIEPING": "Verdieping",
  "BESTUURLIJKE KERNSAMENVATTING": "Kernsamenvatting voor bestuur",
  "KERNSTELLING VAN HET RAPPORT": "Kernstelling",
  "FEITENBASIS": "Feitenbasis",
  "KEUZERICHTINGEN": "Keuzerichtingen",
  "AANBEVOLEN KEUZE": "Voorgestelde keuze",
  "DOORBRAAKINZICHTEN": "Doorbraakinzichten",
  "BESTUURLIJK ACTIEPLAN": "Bestuurlijke acties",
  "BESTUURLIJKE STRESSTEST": "Stressproef",
  "BESTUURLIJKE BLINDE VLEKKEN": "Blinde vlekken",
  "VROEGSIGNALERING": "Vroege signalen",
  "MOGELIJKE ONTWIKKELINGEN": "Scenario-overzicht",
  "OPEN STRATEGISCHE VRAGEN": "Open bestuursvragen",
  "BESLUITGEVOLGEN": "Gevolgen van het besluit",
  "STRATEGISCHE SIGNALEN": "Signalen in de onderstroom",
  "STRATEGISCH PATROON": "Herkenbaar patroon",
  "STRATEGISCHE ERVARING": "Eerdere lessen",
  "PARADOX KWALITEITSCONTROLE": "Toets op scherpte",
  "ONGEMAKKELIJKE WAARHEID": "Wat niet langer ontweken kan worden",
  "BESTUURLIJK DEBAT": "Bestuurlijk debat",
  "STRATEGISCH NARRATIEF": "Bestuurlijk verhaal",
  "BOARD DECISION BRIEF": "Besluitbrief",
  "TECHNISCHE ANALYSE": "Uitvoerings- en kwaliteitsanalyse",
  "HGBCO VERHAALLIJN": "Bestuurlijke verhaallijn",
  "BESTUURLIJKE VERHAALLIJN": "Bestuurlijke verhaallijn",
  "HOE HET SYSTEEM WERKT": "Hoe het systeem werkt",
  "HOE CYNTRA KAN HELPEN": "Waar Cyntra van betekenis kan zijn",
};

export function presentReportSectionTitle(title: string): string {
  const key = String(title || "").trim().toUpperCase();
  return PRESENTATION_TITLES[key] || title;
}
